[package]
name = "burnt_toast"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
paste = "1.0.5"
serde = { version = "1.0", features = ["derive"] }
